CREATE TABLE mudammer (
    agreement_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposed_at TIMESTAMP(6),
    starts_at TIMESTAMP(6),
    ends_at TIMESTAMP(6),
    fee_omr DECIMAL(19,2),
    offered_share_pct DECIMAL(19,2),
    is_active BOOLEAN,
    updated_date TIMESTAMP(6),
    status VARCHAR(255),
    accepted_at TIMESTAMP(6),

    user_user_id BIGINT,
    trainer_user_id BIGINT,
    camel_camel_id BIGINT,

    CONSTRAINT fk_mudammer_user
        FOREIGN KEY (user_user_id) REFERENCES users(user_id),

    CONSTRAINT fk_mudammer_trainer
        FOREIGN KEY (trainer_user_id) REFERENCES trainer_profile(user_id),

    CONSTRAINT fk_mudammer_camel
        FOREIGN KEY (camel_camel_id) REFERENCES camel(camel_id)
);
